---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 2-demo-kutomize-source-git-app
  namespace: flux-system
spec:
  interval: 10s
  path: ./manifest
  prune: true
  sourceRef:
    kind: GitRepository
    name: 2-demo-source-git-app
  targetNamespace: 2-demo
